# site name
siteName: 老王博客
shortName: 王

# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon
favicon: /favicon.ico
# unique avatar
avatarShow: true
avatarImage: /images/avatar.png

# Set default keywords (Use a comma to separate)
keywords: "个人博客, 王风宇个人博客, 个人博客系统, 老王博客, 王风宇"

# your site build time or domain buy time
siteBuildingTime: 02/02/2017


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
topMenu:
   图册: pictures
#   简历: resume

# Left menu of single pages settings
## Notice: faName is FontAwesome style name
leftPagesMenu:
- uri: archives
  title: 归档
  faName: fa-archives
- uri: categories
  title: 分类
  faName: fa-book
- uri: tags
  title: 标签
  faName: fa-tags
- uri: about
  title: 关于
  faName: fa-question-circle


# cover info config
coverTitle: 一个程序员
coverDescription: 一个站在java开发之路上的草根程序员个人博客网站

# sns url
sns:
  github: https://gitee.com/wilco
  send-o: mailto:wfyv@qq.com

# your article copyright or content declare
postDeclare: 如果您觉得本博客还不错，欢迎继续关注本博客，欢迎多提宝贵意见，非常感谢！

# reward of post enable
reward:
  enable: false
  image: /images/donate-qr.jpg

# wechat image
wechat:
  enable: true
  image: /images/qrcode.jpg

# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night

# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
# if is false , default use busuanzi
leancloud_visitors:
  enable: false
  app_id: 
  app_key: 

# Baidu Analytics ID
baidu_analytics: 
# Baidu push
baidu_push: false

#google-site-verification
#https://search.google.com/search-console
google_site_verification: 

## Comments settings.You can choose only ONE to display.
# changyan
changyan:
  enable: false
  appid: 
  appkey: 

# disqus shortName,
disqus_shortname:

# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: false
  githubID: 
  repo: 
  ClientID: 
  ClientSecret: 
  lazy: true